export const Ladies = {
    title: "Womens Fashion",
     image1 : "asets/women/1.jpg",
     image2 : "asets/women/2.jpg",
     image3 : "asets/women/3.jpg",
     image4 : "asets/women/4.jpg",
     image5 : "asets/women/5.jpg",
     image6 : "asets/women/6.jpg",
     price1 : "999 INR",
     price2 : "899 INR",
     price3 : "599 INR",
     price4 : "799 INR",
     price5: "999 INR",
     price6: "899 INR",
} 
export const Gents = {
   title: "Mens Fashion",
     image1 : "asets/mens/1.jpg",
     image2 : "asets/mens/2.jpg",
     image3 : "asets/mens/3.jpg",
     image4 : "asets/mens/4.jpg",
     image5 : "asets/mens/5.jpg",
     image6 : "asets/mens/6.jpg",
     price1: "999 INR",
     price2: "999 INR",
     price3: "1599 INR",
     price4: "1799 INR",
     price5: "699 INR",
     price6: "899 INR",
}
